import { Collection } from "@/features/collections/types/collections.types";

export const collections: Collection[] = [
  {
    id: "1",
    name: "Gatos",
    slug: "gatos",
    description: "Colección de retratos felinos en distintas técnicas y estilos",
    banner: "https://picsum.photos/seed/gatos/800/450",
    status: "published",
    createdAt: new Date("2026-06-02"),
    updatedAt: new Date("2026-08-02"),
  },
  {
    id: "2",
    name: "Retratos silenciosos",
    slug: "retratos-silenciosos",
    description: "Rostros y expresiones capturadas en óleo y carboncillo",
    banner: "https://picsum.photos/seed/retratos-silenciosos/800/450",
    status: "published",
    createdAt: new Date("2026-05-14"),
    updatedAt: new Date("2026-07-28"),
  },
  {
    id: "3",
    name: "Obra en papel",
    slug: "obra-en-papel",
    description: "Piezas sobre papel: acuarela, tinta y técnicas mixtas",
    banner: "https://picsum.photos/seed/obra-en-papel/800/450",
    status: "draft",
    createdAt: new Date("2026-07-10"),
    updatedAt: new Date("2026-07-15"),
  },
  {
    id: "4",
    name: "Paisaje urbano",
    slug: "paisaje-urbano",
    description: "La ciudad como paisaje: calles, edificios y luz",
    banner: "https://picsum.photos/seed/paisaje-urbano/800/450",
    status: "published",
    createdAt: new Date("2026-04-20"),
    updatedAt: new Date("2026-07-01"),
  },
  {
    id: "5",
    name: "Serie azul",
    slug: "serie-azul",
    description: "Exploración cromática en tonos fríos",
    banner: "https://picsum.photos/seed/serie-azul/800/450",
    status: "draft",
    createdAt: new Date("2026-07-18"),
    updatedAt: new Date("2026-07-20"),
  },
  {
    id: "6",
    name: "Naturaleza muerta",
    slug: "naturaleza-muerta",
    description: "Bodegones clásicos con una mirada contemporánea",
    banner: "https://picsum.photos/seed/naturaleza-muerta/800/450",
    status: "published",
    createdAt: new Date("2026-03-11"),
    updatedAt: new Date("2026-06-30"),
  },
  {
    id: "7",
    name: "Abstracciones",
    slug: "abstracciones",
    description: "Formas y color libres de figuración",
    banner: "https://picsum.photos/seed/abstracciones/800/450",
    status: "published",
    createdAt: new Date("2026-02-25"),
    updatedAt: new Date("2026-06-10"),
  },
  {
    id: "8",
    name: "Escenas nocturnas",
    slug: "escenas-nocturnas",
    description: "La ciudad y el paisaje bajo la luz artificial",
    banner: "https://picsum.photos/seed/escenas-nocturnas/800/450",
    status: "archived",
    createdAt: new Date("2025-11-05"),
    updatedAt: new Date("2026-01-22"),
  },
  {
    id: "9",
    name: "Cuerpo y movimiento",
    slug: "cuerpo-y-movimiento",
    description: "Estudios de figura humana en distintas técnicas",
    banner: "https://picsum.photos/seed/cuerpo-y-movimiento/800/450",
    status: "draft",
    createdAt: new Date("2026-08-01"),
    updatedAt: new Date("2026-08-03"),
  },
  {
    id: "10",
    name: "Minimalismo",
    slug: "minimalismo",
    description: "Composiciones reducidas a lo esencial",
    banner: "https://picsum.photos/seed/minimalismo/800/450",
    status: "published",
    createdAt: new Date("2026-01-14"),
    updatedAt: new Date("2026-05-19"),
  },
  {
    id: "11",
    name: "Flora mexicana",
    slug: "flora-mexicana",
    description: "Plantas y flores nativas como motivo central",
    banner: "https://picsum.photos/seed/flora-mexicana/800/450",
    status: "published",
    createdAt: new Date("2025-12-08"),
    updatedAt: new Date("2026-04-02"),
  },
  {
    id: "12",
    name: "Serie en proceso",
    slug: "serie-en-proceso",
    description: "Obras nuevas aún sin curar del todo",
    banner: "https://picsum.photos/seed/serie-en-proceso/800/450",
    status: "draft",
    createdAt: new Date("2026-08-04"),
    updatedAt: new Date("2026-08-05"),
  },
];
